site_name: RCC User Guide
theme:
   name: 'material'
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - "Account and Allocation Management":
    - Overview: account_allocation_management_overview.md
    - Account Management: create_and_manage_accounts.md
    - Allocation Management: request_and_manage_allocations.md
  - "Midway2 and Midway3":
    - Connecting: midway23/midway_connecting.md
    - Getting Started: midway3_getting_started.md
    - Hardware Overview: midway3_hardware_overview.md
    - Connecting to Midway: midway3_connecting.md
    - "Data Management":
      - Data Transfer: midway23/midway3_data_transfer.md
      - Data Storage: midway23/midway3_data_storage.md
      - File System Permissions: midway23/midway3_file_permissions.md
    - "Running Jobs":
      - Overview: midway23/midway_jobs_overview.md
      - Job Management: midway23/midway3_job_management.md
      - Interactive Jobs: midway23/midway3_interactive_jobs.md
      - Batch Jobs: midway23/midway3_batch_jobs.md
      - Example Job Submission Scripts: midway23/example_job_scripts.md
    - "Software":
      - Overview: midway3_software_overview.md
      - "Applications":
        - Ccsm3: midway3_ccsm3.md
        - Cesm: midway3_cesm.md
        - Cp2k: midway3_cp2k.md
        - Gamess: midway3_gamess.md
        - Getpdb: midway3_getpdb.md
        - Gnuplot: midway3_gnuplot.md
        - Gromacs: midway3_gromacs.md
        - Hoomd: midway3_hoomd.md
        - Lammps: midway3_lammps.md
        - Mitgcm: midway3_mitgcm.md
        - Namd: midway3_namd.md
        - Openfoam: midway3_openfoam.md
      - "Compilers":
        - GNU: midway3_gnu.md
        - Intel: midway3_intel.md
        - PGI: midway3_pgi.md
        - Nvidia: midway3_nvidia.md
      - "Debugging":
        - Ddt: midway3_ddt.md
        - Hpctoolkit: midway3_hpctoolkit.md 
        - Papi: midway3_papi.md 
        - Valgrind: midway3_valgrind.md
      - "Environments":
        - R: midway3_r.md
        - Mathematica: midway3_mathematica.md
        - Matlab: midway3_matlab.md
        - Perl: midway3_perl.md
        - Python: midway3_python.md
        - Spark: midway3_spark.md
        - Stata: midway3_stata.md
      - "Libraries": 
        - Fftw: midway3_fftw.md
        - Mpi: midway3_mpi.md
        - Netcdf: midway3_netcdf.md
      - "Commonly Used Applications":
        - Python and Conda: midway3_python.md
        - Jupyter: midway3_jupyter.md
        - Tensorflow and PyTorch: midway3_tf_pytorch.md
      - List of All Software: midway3_software_list.md
      - Request New Software: midway3_software_requests.md
    - Troubleshooting and FAQ: midway3_troubleshooting.md
  - "MidwayR":
      - Overview: midwayr/midwayR_overview.md
  - "Other Systems":
    - "Beagle3":
      - Overview: other_systems/beagle3_overview.md
    - "DaLI":
      - Overview: other_systems/dali_overview.md
    - "MidwaySSD":
      - Overview: other_systems/midwayssd_overview.md
    - "Skyway":
      - Overview: other_systems/skyway_overview.md
  - "Facility Policies":
    - facility_policies.md
  - "Tutorials":
    - tutorial_01.md
  - "Help":
    - Glossary: glossary.md
    - Frequently Asked Questions: general_faq.md
    - Contact Us: contact_us.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - wikilinks
  - tables